const $=s=>document.querySelector(s), money=n=>'P'+Number(n).toLocaleString('en-BW');
const countries={Botswana:['Gaborone','Francistown','Maun','Kasane','Palapye','Serowe','Mahalapye','Lobatse','Nata'],'South Africa':['Johannesburg','Pretoria','Polokwane','Rustenburg','Cape Town','Durban'],'Zimbabwe':['Harare','Bulawayo','Victoria Falls','Plumtree','Gweru'],'Zambia':['Lusaka','Livingstone','Kazungula','Kitwe','Ndola']};
const state={mode:localStorage.rw_mode||'customer',page:'home',trips:JSON.parse(localStorage.rw_trips||'null')||[
{id:'TR-2201',from:'Johannesburg',to:'Gaborone',date:'16 Jul',time:'06:30',runner:'Mpho K.',vehicle:'Toyota Fortuner',rating:4.9,kg:42,spaces:4,services:['Shopping','Parcels','Documents'],earn:3850,stops:['Pretoria','Polokwane','Tlokweng Border'],status:'Leaving Soon'},
{id:'TR-2202',from:'Gaborone',to:'Maun',date:'15 Jul',time:'14:00',runner:'Kagiso M.',vehicle:'Toyota Hilux',rating:4.8,kg:68,spaces:7,services:['Parcels','Documents','Medicine'],earn:2100,stops:['Mahalapye','Palapye','Nata'],status:'Today'},
{id:'TR-2203',from:'Harare',to:'Francistown',date:'17 Jul',time:'08:00',runner:'Tafadzwa N.',vehicle:'Nissan X-Trail',rating:4.7,kg:34,spaces:5,services:['Shopping','Parcels'],earn:2980,stops:['Bulawayo','Plumtree','Ramokgwebana'],status:'Tomorrow'},
{id:'TR-2204',from:'Lusaka',to:'Kasane',date:'18 Jul',time:'07:15',runner:'Chanda P.',vehicle:'Toyota Quantum',rating:4.9,kg:96,spaces:9,services:['Parcels','Business Stock','Documents'],earn:4620,stops:['Kafue','Livingstone','Kazungula'],status:'Upcoming'}],requests:JSON.parse(localStorage.rw_requests||'null')||[]};
const menus={customer:[['home','⌂ Home'],['trips','🚗 Trip Marketplace'],['requests','📦 My Requests'],['live','📍 Live Journey'],['wallet','◈ Wallet & Escrow']],runner:[['runner','⌂ Runner Home'],['announce','✈ Announce Trip'],['mytrips','🚗 My Trips'],['matches','⚡ Smart Matches'],['live','📍 My Journey'],['earnings','◈ Earnings']]};
const titles={home:'Home',trips:'Trip Marketplace',requests:'My Requests',live:'Live Journey',wallet:'Wallet & Escrow',runner:'Runner Home',announce:'Announce Trip',mytrips:'My Trips',matches:'Smart Matches',earnings:'Earnings'};
function save(){localStorage.rw_mode=state.mode;localStorage.rw_trips=JSON.stringify(state.trips);localStorage.rw_requests=JSON.stringify(state.requests)}
function toast(t){$('.toast').textContent=t;$('.toast').classList.add('show');setTimeout(()=>$('.toast').classList.remove('show'),2200)}
function badge(s){return `<span class='badge ${s==='Leaving Soon'||s==='Today'?'success':s==='Tomorrow'?'warning':'neutral'}'>${s}</span>`}
function routeSearch(){return `<div class='route-search'><label>From<input id='from' list='cities' placeholder='City or country'></label><button>⇄</button><label>To<input id='to' list='cities' placeholder='Destination'></label><label>Date<input type='date'></label><button class='primary' id='find'>Find Trips</button><datalist id='cities'>${Object.entries(countries).flatMap(([c,a])=>a.map(x=>`<option value='${x}, ${c}'>`)).join('')}</datalist></div>`}
function tripCard(t){return `<div class='card trip-card'><div>${badge(t.status)}<h3>${t.from} → ${t.to}</h3><p>${t.date} • ${t.time} • ${t.runner} • ★ ${t.rating}</p><div class='pills'><span>${t.vehicle}</span><span>${t.kg} kg</span><span>${t.spaces} spaces</span>${t.services.map(x=>`<span>${x}</span>`).join('')}</div></div><div class='price'><small>Potential earnings</small><strong>${money(t.earn)}</strong><button class='primary view' data-id='${t.id}'>View Trip</button></div></div>`}
function heat(){return `<div class='heat'>${[['Johannesburg → Gaborone',96],['Harare → Francistown',82],['Gaborone → Maun',67],['Lusaka → Kasane',61]].map(x=>`<div><b>${x[0]}</b><i><em style='width:${x[1]}%'></em></i><span>${x[1]>80?'High':'Medium'}</span></div>`).join('')}</div>`}
function home(){return `<div class='hero'><div><small>BOTSWANA • SOUTH AFRICA • ZIMBABWE • ZAMBIA</small><h2>Someone is already going there. Let RunWise carry it.</h2><p>Find a trip, send a parcel, request shopping, or announce your own journey and earn along the way.</p></div><div class='wallet'><span>Trips leaving soon</span><strong>4</strong></div></div><div class='service-grid'>${[['🚗','Find a Trip','trips'],['📦','Send a Parcel','parcel'],['🛒','Shopping Request','shopping'],['📄','Documents','documents'],['💊','Medicine','medicine'],['🎁','Gift Delivery','gift'],['🚚','Large Item','large'],['✈️','Announce a Trip','announce']].map(x=>`<button class='service' data-act='${x[2]}'><b>${x[0]}</b><strong>${x[1]}</strong></button>`).join('')}</div><div class='section'><h3>Search a route</h3></div><div class='card'>${routeSearch()}</div><div class='section'><h3>Leaving soon</h3></div><div class='grid g2'>${state.trips.map(tripCard).join('')}</div><div class='section'><h3>Demand heat map</h3></div><div class='card'>${heat()}</div>`}
function trips(){return `<div class='card'>${routeSearch()}</div><div class='section'><h3>Trip board</h3><button id='announceBoard'>Announce your trip</button></div><div class='grid g2'>${state.trips.map(tripCard).join('')}</div>`}
function requests(){return `<div class='section'><h3>Your requests</h3><button id='newReq' class='primary'>+ Post Request</button></div><div class='card'>${state.requests.length?state.requests.map(r=>`<div class='order'><b>${r.type}</b><span>${r.from} → ${r.to}</span><span>${money(r.value)}</span><span class='badge warning'>Waiting</span></div>`).join(''):'<p>No requests yet.</p>'}</div>`}
function live(){let t=state.trips[0],steps=['Shopping complete in Johannesburg','Parcel collected in Pretoria','Fuel stop in Polokwane','Border processing at Tlokweng','Entered Botswana','Gaborone deliveries started','Your delivery'];return `<div class='live-banner'><b>${state.mode==='runner'?'My active journey':'Your item is moving'}</b><span>${t.from} → ${t.to}</span></div><div class='grid g2'><div class='card map'><div class='route'></div><div class='pin a'></div><div class='pin b'></div><div class='car'>🚙</div></div><div class='card'><small>${t.id}</small><h3>${t.runner} • ${t.vehicle}</h3><p>Current location: Polokwane • ETA 16:45</p><div class='progress'><i style='width:46%'></i></div>${steps.map((s,i)=>`<div class='step ${i<2?'done':i===2?'now':''}'><i></i><div><b>${s}</b><small>${i<2?'Completed':i===2?'Live now':'Pending'}</small></div></div>`).join('')}</div></div><div class='grid g4 stats'><div class='card stat'><span>Distance left</span><strong>312 km</strong></div><div class='card stat'><span>Your position</span><strong>3 of 8</strong></div><div class='card stat'><span>Journey followers</span><strong>14</strong></div><div class='card stat'><span>Next update</span><strong>Border</strong></div></div>`}
function wallet(){return `<div class='grid g3'><div class='card stat'><span>Wallet balance</span><strong>P2,450</strong></div><div class='card stat'><span>Funds in escrow</span><strong>P6,840</strong></div><div class='card stat'><span>Pending releases</span><strong>P1,920</strong></div></div>`}
function runner(){return `<div class='hero'><div><small>RUNNER MODE</small><h2>Turn your next journey into earnings.</h2><p>Announce your route and RunWise finds requests along the way.</p></div><div class='wallet'><span>Potential this week</span><strong>P8,920</strong></div></div><div class='grid g4 stats'><div class='card stat'><span>Compatible requests</span><strong>23</strong></div><div class='card stat'><span>Active journeys</span><strong>1</strong></div><div class='card stat'><span>Rating</span><strong>4.9</strong></div><div class='card stat'><span>On-time rate</span><strong>97%</strong></div></div><div class='section'><h3>Demand heat map</h3></div><div class='card'>${heat()}</div>`}
function announce(){return `<div class='card'><h3>Announce your journey</h3>${tripForm()}</div>`}
function tripForm(){return `<form id='tripForm'><label>From country<select name='fc'>${opts('South Africa')}</select></label><label>From city<input name='from' required></label><label>To country<select name='tc'>${opts('Botswana')}</select></label><label>To city<input name='to' required></label><label>Date<input type='date' name='date' required></label><label>Time<input type='time' name='time' required></label><label>Vehicle<input name='vehicle' required placeholder='Toyota Hilux'></label><label>Capacity kg<input name='kg' type='number' value='40' required></label><label class='full'>Intermediate stops<input name='stops' placeholder='Pretoria, Polokwane, Tlokweng Border'></label><div class='estimate full'><span>Estimated smart matches</span><strong>23 requests • Potential P4,860</strong></div><button class='primary full'>Publish Trip</button></form>`}
function mytrips(){return `<div class='section'><h3>Your announced trips</h3></div><div class='grid g2'>${state.trips.slice(0,2).map(tripCard).join('')}</div>`}
function matches(){return `<div class='grid g3'>${[['Shopping','Johannesburg → Gaborone','P420'],['Documents','Pretoria → Palapye','P260'],['Medicine','Polokwane → Francistown','P310']].map(x=>`<div class='card'><small>SMART MATCH</small><h3>${x[0]}</h3><p>${x[1]}</p><strong>${x[2]}</strong><button class='primary accept'>Accept Match</button></div>`).join('')}</div>`}
function earnings(){return `<div class='grid g4 stats'><div class='card stat'><span>Available</span><strong>P3,840</strong></div><div class='card stat'><span>This month</span><strong>P8,920</strong></div><div class='card stat'><span>Completed trips</span><strong>14</strong></div><div class='card stat'><span>Average</span><strong>P637</strong></div></div>`}
function opts(sel){return Object.keys(countries).map(c=>`<option ${c===sel?'selected':''}>${c}</option>`).join('')}
function view(){if(state.mode==='runner')return state.page==='announce'?announce():state.page==='mytrips'?mytrips():state.page==='matches'?matches():state.page==='live'?live():state.page==='earnings'?earnings():runner();return state.page==='trips'?trips():state.page==='requests'?requests():state.page==='live'?live():state.page==='wallet'?wallet():home()}
function render(){$('#nav').innerHTML=menus[state.mode].map(x=>`<button class='nav-btn ${state.page===x[0]?'active':''}' data-page='${x[0]}'>${x[1]}</button>`).join('');document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});$('#portalName').textContent=state.mode==='runner'?'RUNNER MODE':'RUNWISE MARKETPLACE';$('#pageTitle').textContent=titles[state.page]||'Home';$('#modeBtn').textContent=state.mode==='runner'?'Switch to Customer':'Switch to Runner';$('#primaryAction').textContent=state.mode==='runner'?'+ Announce Trip':'+ Post Request';$('#content').innerHTML=view();bind()}
function bind(){document.querySelectorAll('.service').forEach(b=>b.onclick=()=>{let a=b.dataset.act;if(a==='trips'){state.page='trips';render()}else if(a==='announce'){state.mode='runner';state.page='announce';save();render()}else openRequest(a)});document.querySelectorAll('.view').forEach(b=>b.onclick=()=>openTrip(b.dataset.id));document.querySelectorAll('.accept').forEach(b=>b.onclick=()=>toast('Match accepted'));let f=$('#find');if(f)f.onclick=()=>toast('Matching trips found');let n=$('#newReq');if(n)n.onclick=()=>openRequest('parcel');let a=$('#announceBoard');if(a)a.onclick=()=>{state.mode='runner';state.page='announce';save();render()};let tf=$('#tripForm');if(tf)tf.onsubmit=submitTrip}
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.remove('hidden')}
function openRequest(type='parcel'){openModal('Post a Request',`<form id='reqForm'><label>Type<select name='type'><option>${type}</option><option>Shopping</option><option>Parcel</option><option>Documents</option><option>Medicine</option><option>Gift</option><option>Large Item</option></select></label><label>From city<input name='from' required></label><label>To city<input name='to' required></label><label>Estimated value<input type='number' name='value' value='300'></label><label class='full'>Details<textarea name='details'></textarea></label><button class='primary full'>Post Request</button></form>`);$('#reqForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);state.requests.unshift({type:f.get('type'),from:f.get('from'),to:f.get('to'),value:+f.get('value')});save();$('#modal').classList.add('hidden');state.page='requests';render();toast('Request posted and runners notified')}}
function openTrip(id){let t=state.trips.find(x=>x.id===id);openModal(`${t.from} → ${t.to}`,`<p><b>${t.runner}</b> • ${t.vehicle} • ★ ${t.rating}</p><h3>Route stops</h3><p>${[t.from,...t.stops,t.to].join(' → ')}</p><div class='estimate'><span>Capacity</span><strong>${t.kg} kg • ${t.spaces} spaces</strong></div><button id='matchTrip' class='primary'>Match My Request</button>`);$('#matchTrip').onclick=()=>openRequest('parcel')}
function submitTrip(e){e.preventDefault();let f=new FormData(e.target);state.trips.unshift({id:'TR-'+Math.floor(3000+Math.random()*999),from:f.get('from'),to:f.get('to'),date:f.get('date'),time:f.get('time'),runner:'Tefo',vehicle:f.get('vehicle'),rating:5,kg:+f.get('kg'),spaces:6,services:['Shopping','Parcels','Documents'],earn:4860,stops:f.get('stops').split(',').map(x=>x.trim()).filter(Boolean),status:'Upcoming'});save();state.page='mytrips';render();toast('Trip published. 23 smart matches found')}
$('#modeBtn').onclick=()=>{state.mode=state.mode==='runner'?'customer':'runner';state.page=state.mode==='runner'?'runner':'home';save();render()};$('#primaryAction').onclick=()=>state.mode==='runner'?(state.page='announce',render()):openRequest('parcel');$('#notify').onclick=()=>toast('3 new route matches');$('#close').onclick=()=>$('#modal').classList.add('hidden');render();
